### ISSUE TITLE
Index out of range when I select country from search result

### ISSUE THREAD

**Issue by emoonadev** [mobven/CountryPicker#15] opened 2022-08-09 13:38 UTC
Hi,

![Screen Shot 2022-08-09 at 16 38 07](https://user-images.githubusercontent.com/35075841/183663117-4858bd41-b85c-4b9e-817a-1ea1553bc19a.png)

**Comment by Rashidium** [comment] 2022-08-09 14:23
please mention the version you are using

**Comment by Rashidium** [comment] 2022-08-09 14:23
this should be fixed on the latest version 1.0.4

**Comment by emoonadev** [comment] 2022-08-09 14:30
Not fixed on 1.0.4

**Comment by Rashidium** [comment] 2022-08-09 14:32
would you please describe how the scenario is? i would appreciate if you can specify what's the ui framework used, swiftui or uikit?

**Comment by emoonadev** [comment] 2022-08-09 14:39
I use UIKIT, when I start seach for "unit" and select united state the crash occur
![ezgif-3-66ab79c1a7](https://user-images.githubusercontent.com/35075841/183677815-f63cf3e2-7181-470a-a3c0-35ea9c482348.gif)

**Comment by Rashidium** [comment] 2022-08-09 15:23
interesting. i was sure fixed it with 1.0.4. let me check and get you back.

**Comment by emoonadev** [comment] 2022-08-09 16:49
Thank I hope it will be fixed quickly because the lib look great, and our release it will be in few days. I don’t want to switch to another lib

**Comment by Rashidium** [comment] 2022-08-10 08:45
hello @emoonadev .  I've checked in the sample app of 1.0.4 and I couldn't reproduce the crash. Can you double check whether your version is 1.0.4? You can see the version you're using in file inspector of the xcode where SPM package versions are visible. It should contain CountryPicker (1.0.4).

**Comment by emoonadev** [comment] 2022-08-10 08:46
Yes the version is 1.0.4

**Comment by Rashidium** [comment] 2022-08-10 08:59
Yes I could reproduce it. It's strange that on dismiss ui text field updates suggestion. I thought this is only behavior of UITextField.onEditingChanged. But somehow its same for `shouldChangeCharactersIn`.
I'm merging your PR with tag 1.0.5. Thanks for contribution @emoonadev  🍻

**Closed by Rashidium** 2022-08-10 08:59 UTC
